config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  root 'schedules#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, :start_date, :end_date, presence: true
    validate :judge_end_date
    
    def judge_end_date
        if self.end_date && self.start_date && self.end_date < self.start_date || 
            self.end_date && self.end_date < Date.today || !self.end_date
           
           self.errors.add(:end_date, :early)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to :schedules, notice: 'スケジュールを登録しました' }
        format.json { render :index, status: :created, location: @schedule }
      else
        flash.alert = "スケジュールを登録できませんでした"
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to  :schedules, notice: 'スケジュールが更新されました' }
        format.json { render :index, status: :ok, location: @schedule }
      else
        flash.alert = "スケジュールを更新できませんでした"
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'スケジュールを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:title, :start_date, :end_date, :week_end, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <%= render "shared/header" %>
    </header>
    <main class="flex-shrink-0">
      <%= yield %>
    </main>
    <footer class="footer mt-auto">
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class="container-fluid py-3">
  <% if flash.alert %>
    <div class="pt-5 col-4">
      <p class="alert"><%= flash.alert %></p>  
    </div>
  <% else %>
    <h2 class="pt-5 pb-3">スケジュールの編集</h2>
  <% end %>
  
  <%= form_with(model: @schedule) do |form| %>
    <%= render 'shared/form', form: form %>
    <ul class="pt-3">
      <li>
        <%= form.submit "スケジュールの編集を完了する" %>
      </li>
      <li>
        <%= link_to 'スケジュール一覧に戻る', schedules_path %>
      </li>
    </ul>
  <% end %>
</div>

app/views/schedules/index.html.erb
<div class="container-fluid py-3">
  
  <h2 class="pt-5 pb-3">スケジュール一覧</h2>
  
  <% if notice %>
    <p id="notice" class="info col-4 py-2"><%= notice %></p>
  <% end %>
  
  <% if @schedules.present? %>
    <table class="col-md-10 col-sm-12 schedules-list">
      <thead>
        <tr>
          <th>ID</th>
          <th>タイトル</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>終日</th>
          <th>スケジュール更新日時</th>
          <th>確認</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.id %></td>
            <td><%= schedule.title %></td>
            <td><%= schedule.start_date&.strftime('%Y年%m月%d日') %></td>
            <td><%= schedule.end_date&.strftime('%Y年%m月%d日') %></td>
            <td><%= schedule.week_end == true ? "○" : "" %></td>
            <td><%= schedule.updated_at&.strftime('%Y年%m月%d日 %H時%M分') %></td>
            <td><%= link_to '確認', schedule %></td>
            <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
            <td><%= link_to '削除', schedule, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>スケジュールがありません</p>
  <% end %>
    
  <p class="pt-3">
    <%= link_to 'スケジュール新規登録', new_schedule_path %>
  </p>
</div>

app/views/schedules/new.html.erb
<div class="container-fluid py-3">
  <% if flash.alert %>
    <div class="pt-5 col-4">
      <p class="alert"><%= flash.alert %></p>  
    </div>
  <% else %>
    <h2 class="pt-5 pb-3">スケジュール新規作成</h2>
  <% end %>
  
  <%= form_with(model: @schedule) do |form| %>
    <%= render 'shared/form', form: form %>
    <ul class="pt-3">
      <li>
        <%= form.submit "スケジュールを新規作成する" %>
      </li>
      <li>
        <%= link_to 'スケジュール一覧に戻る', schedules_path %>
      </li>
    </ul>
  <% end %>
</div>

app/views/schedules/show.html.erb
<div class="container-fluid py-3">
  
  <h2 class="pt-5 pb-3">スケジュール詳細</h2>
  
  <p id="notice"><%= notice %></p>
  
  <table class="col-md-6 schedule-detail">
    <tbody>
      <tr>
        <th>タイトル</th>
        <td><%= @schedule.title %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @schedule.start_date&.strftime('%Y年%m月%d日') %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @schedule.end_date&.strftime('%Y年%m月%d日') %></td>
      </tr>
      <tr>
        <th>終日</th>
        <td><%= @schedule.week_end == true ? "○" : "" %></td>
      </tr>
      <tr>
        <th>メモ</th>
        <td class="memo"><%= simple_format(@schedule.content) %></td>
      </tr>
    </tbody>
  </table>
  
  <ul class="pt-3">
    <li>
      <%= link_to 'スケジュール一覧に戻る', schedules_path %>
    </li>
    <li>
      <%= link_to 'スケジュールを削除', @schedule, method: :delete, data: { confirm: '本当に削除しますか?' } %>
    </li>
    <li>
      <%= link_to 'スケジュールを編集する', edit_schedule_path(@schedule) %>
    </li>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid">
 <h1>
    <% if params['action'] == "index" %>
        <%= "現在の日時 : #{ Date.current&.strftime('%Y年%m月%d日') }　スケジュール合計 : #{Schedule.all.count}" %>
    <% else %>
        <%= "現在の日時 : #{ Date.current&.strftime('%Y年%m月%d日') }" %>
    <% end %>
 </h1>
</div>

app/views/shared/_form.html.erb
  <% if @schedule.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @schedule.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <table class="schedule-form col-5">
      <tbody>
        <tr>
          <th><%= form.label :title %></th>
          <td class="form-group"><%= form.text_field :title, class: "form-control" %></td>
        </tr>
        <tr>
          <th><%= form.label :start_date %></th>
          <td class="form-group"><%= form.date_field :start_date, class: "form-control" %></td>
        </tr>
        <tr>
          <th><%= form.label :end_date %></th>
          <td class="form-group"><%= form.date_field :end_date, class: "form-control end-date" %></td>
        </tr>
        <tr>
          <th><%= form.label :week_end %></th>
          <td>
            <%= form.check_box :week_end %>
            <p>終日の場合はチェックを入れます</p>
          </td>
        </tr>
        <tr>
          <th><%= form.label :content %></th>
          <td class="form-group"><%= form.text_area :content, class: "form-control memo" %></td>
        </tr>
      </tbody>
    </table>

app/views/shared/_header.html.erb
<div class="container-fluid">
 <h1>Ruby on Rails スケジュール管理アプリ</h1>
</div>